wikidot_username = "Notifier"
config_wiki = "notifications"
user_config_category = "notify"
wiki_config_category = "wiki"
overrides_url = "https://notifications.wdfiles.com/local--code/overrides/1"
gmail_username = "wikidotnotifier@gmail.com"
database_driver = "notifier.database.drivers.sqlite.SqliteDriver"

[path]
# Paths:
# . -> cwd
# @ -> package root
# ? -> this config file
lang = "@/lang.toml"