[notifier]
wikdot_username = "Notifier"
config_wiki = "notifications"
user_config_category = "notify"
site_config_category = "site"
overrides_url = "https://notifications.wdfiles.com/local--code/overrides/1"
