[tool.poetry]
name = "notifier"
version = "0.0.0"
description = "Wikidot notifications"
authors = ["Ross Williams <rossjrw@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
APScheduler = "^3.7.0"
pyscp = "^1.1.18"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
black = "^21.7b0"

[tool.black]
line-length = 79
target-version = ['py38']
skip-string-normalization = true
include = '\.pyi?$'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
