[base]
link_site = "http://notifications.wikidot.com"
link_your_config = "{link_site}/redirect-to-your-config"
link_unsubscribe = "{link_site}/faq#stop"
link_info_learning = "{link_site}/faq#learning"
link_info_automatic = "{link_site}/faq#auto"

body = """
{intro}

{wikis}

{outro}
"""
wiki = """
++ {wiki_name}

{categories}
"""
category = """
+++ {category_name}

{summary}

[[ul style="list-style-type: ':open_mailbox_with_raised_flag: '"]]
{threads}
[[/ul]]
"""
thread = """
[[li]]
**{thread_opener} [{thread_url} {thread_title}]** plural({thread_has_creator}||-- [[*user {thread_creator}]]) -- {date}
{replies_section}
{posts_section}
[[/li]]
"""
replies_section = """
[[ul style="list-style-type: ':package: '"]]
{posts_replied_to}
[[/ul]]
"""
post_replied_to = """
[[li]]
**{post_replies_opener} [{post_url} {post_title}]** -- {date}

{posts_section}
[[/li]]
"""
posts_section = """
[[ul style="list-style-type: ':envelope: '"]]
{posts}
[[/ul]]
"""
post = """
[[li]]
**[{post_url} {post_title}]** -- [[*user {post_author}]] -- {date}
<br>
**|** ##grey|//{snippet}//##
[[/li]]
"""
date = """[[date {timestamp} format="%d %b %Y %H:%M:%S|agohover"]]"""
outro = """
-----

[[=]]
+ :open_mailbox_with_lowered_flag:

-----

{unsub_footer}
[[/=]]
"""

[en]
frequency_hourly = "hourly"
frequency_daily = "daily"
frequency_weekly = "weekly"
frequency_monthly = "monthly"
subject = "[Forum Notifications] {post_count} new posts"
intro = """|
Hello! This is your {frequency} notification digest from {link_site}, notifying
you of new posts to threads that you're subscribed to.

Not including any subscriptions that have been removed as a result of your
manual unsubscriptions, this service is keeping track of {sub_count}
plural({sub_count}|subscription|subscriptions) for you:

* {manual_sub_count} manual
plural({manual_sub_count}|subscription|subscriptions), as defined in
[{link_your_config} your user configuration].

* {auto_thread_sub_count} automatic thread
plural({auto_thread_sub_count}|subscription|subscriptions) and
{auto_post_sub_count} automatic post
plural({auto_post_sub_count}|subscription|subscriptions). The service is
[{link_info_learning} still learning] about your automatic subscriptions, so
expect this number to increase over time. [{link_info_automatic} Learn what
constitutes an automatic subscription.]

This account ([[*user Notifier]]) is automated -- any response to this
message will be ignored. If there are any problems, contact me ([[*user
Croquembouche]]) directly.

-----

[[=]]<>+ :closed_mailbox_with_raised_flag:<>[[/=]]

-----
"""
unsub_footer = "Unsubscribe from these notifications: {link_unsubscribe}"
main_summary = "You have {summary} from {wiki_count} plural({wiki_count}|wiki|wikis)"
summary = """|
{notification_count} plural({notification_count}|notification|notifications)
in {thread_count} plural({thread_count}|thread|threads)
"""
unknown_category_name = "Other"
thread_opener = "Thread:"
post_replies_opener = "Replies to your post:"
untitled_post_title = "(untitled post)"

[vi]
frequency_hourly = "hàng giờ"
frequency_daily = "hàng ngày"
frequency_weekly = "hàng tuần"
frequency_monthly = "hàng tháng"
subject = "[Thông Báo Diễn Đàn] {post_count} post mới"
intro = """|
Xin chào! Đây là hệ thống thông báo {frequency} của bạn từ {link_site}, hiển thị
thông báo về các bài post mới được đăng vào trang thread mà bạn đăng kí
theo dõi.

Trừ đi các phần mà bạn đã hủy đăng kí thông qua chỉnh sửa đăng kí thủ công,
dịch vụ này hiện đang theo dõi {sub_count} đăng kí cho bạn, bao gồm:

* {manual_sub_count} mẫu đăng kí thủ công, theo như cài đặt tại
[{link_your_config} bản điều chỉnh người dùng của bạn].

* {auto_thread_sub_count} thread được đăng kí tự động và
{auto_post_sub_count} post đăng kí tự động. Dịch vụ hiện vẫn
[{link_info_learning} đang học hỏi] về các bản đăng kí tự động của bạn, vì
thế con số này có thể tăng thêm theo thời gian. [{link_info_automatic} Tìm hiểu
về những yếu tố cấu thành bản đăng kí tự động.]

Tài khoản ([[*user Notifier]]) này được chạy tự động -- bất kể tin nhắn
gửi đến tài khoản đều bị bỏ qua. Nếu có khúc mắc, vui lòng liên hệ ([[*user
Croquembouche]]) trực tiếp.

-----

[[=]]<>+ :closed_mailbox_with_raised_flag:<>[[/=]]

-----
"""
unsub_footer = "Hủy đăng kí những thông báo này: {link_unsubscribe}"
main_summary = "Bạn có {summary} từ {wiki_count} wiki"
summary = """|
{notification_count} thông báo tại {thread_count} thred
"""
unknown_category_name = "Khác"
thread_opener = "Thread:"
post_replies_opener = "Phản hồi lại post của bạn:"
untitled_post_title = "(post không có tiêu đề)"

[fr]
link_site = "http://commandemento5.wikidot.com/notifications"
link_your_config = "http://notifications.wikidot.com/redirect-to-your-config"
link_unsubscribe = "{link_site}#stop"
link_info_learning = "{link_site}#learning"
link_info_automatic = "{link_site}#auto"

frequency_hourly = "de la dernière heure"
frequency_daily = "journalier"
frequency_weekly = "hebdomadaire"
frequency_monthly = "mensuel"
subject = "[Notifications Forum] {post_count} nouveaux messages"
intro = """|
Bonjour ! Voici votre récapitulatif de [{link_site} notifications] {frequency}, vous informant de tous les nouveaux messages sur les fils auxquels vous vous êtes abonné·e.

Ce service vous tient au courant des derniers messages de {sub_count} plural({sub_count}|abonnement|abonnements), sources supprimées manuellement non incluses.

* {manual_sub_count} plural({manual_sub_count}|abonnement|abonnements) plural({manual_sub_count}|manuel|manuels), comme définis dans [{link_your_config} vos paramètres d'utilisateur].

* {auto_thread_sub_count} plural({auto_thread_sub_count}|abonnement automatique à un fil|abonnements automatiques à des fils) et {auto_post_sub_count} à plural({auto_post_sub_count}|un message|des messages). Ce service [{link_info_learning} apprend encore] de vos abonnements automatiques ; attendez-vous à voir ce nombre augmenter avec le temps. [{link_info_automatic} Apprenez comment marchent les abonnements automatiques.]

Ce compte ([[*user Notifier]]) est automatisé -- les réponses à ce message ne seront pas prises en compte. Si vous avez un problème, contactez directement [[*user
Croquembouche]] (en anglais).

-----

[[=]]<>+ :closed_mailbox_with_raised_flag:<>[[/=]]

-----
"""
unsub_footer = "Se désinscrire de ces notifications : {link_unsubscribe}"
main_summary = "Vous avez {summary} de {wiki_count} plural({wiki_count}|wiki|wikis)"
summary = """|
{notification_count} plural({notification_count}|notification|notifications)
sur {thread_count} plural({thread_count}|fil|fils)
"""
unknown_category_name = "Autres"
thread_opener = "Fil :"
post_replies_opener = "Réponses à votre message :"
untitled_post_title = "(message sans titre)"

[es]
frequency_hourly = "de cada hora"
frequency_daily = "diario"
frequency_weekly = "semanal"
frequency_monthly = "mensual"
subject = "[Notificaciones del Foro] {post_count} nuevos mensajes"
intro = """|
¡Hola! Este es el resumen {frequency} de notificaciones de {link_site}, avisándote
de las nuevas respuestas a hilos a los que estás suscrito.
No incluye ninguna suscripción que haya sido removida como resultado de tus
desuscripciones manuales, este servicio mantiene seguimiento de {sub_count}
plural({sub_count}|suscripción|suscripciones) para ti:

* {manual_sub_count}
plural({manual_sub_count}|suscripción|suscripciones) manuales, como se define en
[{link_your_config} tu configuración de usuario].

* {auto_thread_sub_count} hilos automáticos
plural({auto_thread_sub_count}|suscrito|suscritos) y
{auto_post_sub_count} publicaciones automáticas
plural({auto_post_sub_count}|suscritas|suscritas). El servicio aún
[{link_info_learning} está aprendiendo] sobre tus suscripciones automáticas, así que espera que este número crezca con el tiempo. [{link_info_automatic} Aprende qué constituye una suscripción automática.]

La cuenta ([[*user Notifier]]) está automatizada -- cualquier respuesta a este
mensaje será ignorada. Si hay cualquier problema, contacta directamente conmigo, ([[*user
Croquembouche]]).

-----

[[=]]<>+ :closed_mailbox_with_raised_flag:<>[[/=]]

-----
"""
unsub_footer = "Desuscribirse de estas notificaciones: {link_unsubscribe}"
main_summary = "Tienes {summary} de {wiki_count} plural({wiki_count}|wiki|wikis)"
summary = """|
{notification_count} plural({notification_count}|notificación|notificaciones)
en {thread_count} plural({thread_count}|hilo|hilos)
"""
unknown_category_name = "Otros"
thread_opener = "Hilo:"
post_replies_opener = "Respuestas:"
untitled_post_title = "(publicación sin título)"

[ja]
frequency_hourly = "一時間ごと"
frequency_daily = "一日ごと"
frequency_weekly = "一週間ごと"
frequency_monthly = "ひと月ごと"
subject = "[フォーラム通知] {post_count}個の新しいポスト"
intro = """|
こんにちは！こちらは{link_site}から{frequency}の通知です。
あなたの登録したスレッドに新しいポストが投稿されたので、通知をします。
これは、あなたが手動で登録解除したスレッドを含んでいません。
本サービスにあなたが登録したスレッド数は{sub_count}個です。
そのうち、[{link_your_config} あなたのユーザー設定ページ]にある通り、{manual_sub_count}個が手動登録です。
自動登録されたスレッドは{auto_thread_sub_count}個で、ポストは{auto_post_sub_count}個です。
本サービスはあなたの自動登録を[{link_info_learning} 学習しています]。今後、自動登録の個数が増加する場合があります。
[{link_info_automatic} 自動登録の構成については、こちらを参照してください。]
本アカウント([[*user Notifier]])は自動であり、いかなる返信対応もできません。問題があるようでしたら、[[*user Croquembouche]]に直接ご連絡ください。

-----

[[=]]<>+ :closed_mailbox_with_raised_flag:<>[[/=]]

-----
"""
unsub_footer = "[{link_unsubscribe} 登録を解除する]"
main_summary = "{wiki_count}個のwikiからの{summary}です。"
summary = """|
{thread_count}個のスレッドに{notification_count}件の通知
"""
unknown_category_name = "その他"
thread_opener = "スレッド:"
post_replies_opener = "返信:"
untitled_post_title = "(無題のポスト)"