name: tests
on:
  # Run on push to main
  push:
    paths:
      - 'notifier/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'config.toml'
      - '.github/workflows/tests.yml'
    branches: [ main ]
    
  # Run on PR
  pull_request:
    paths:
      - 'notifier/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'config.toml'
      - '.github/workflows/tests.yml'

  # Run manually
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Cache Python dependencies
        uses: actions/cache@v2
        id: cached-poetry-dependencies
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install Python dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction
      - name: Start MySQL
        run: |
          sudo systemctl start mysql.service
          mysql -uroot -proot -e 'CREATE DATABASE wikidot_notifier_test;'
      - name: Run tests
        run: poetry run pytest --notifier-config config.toml --notifier-auth .github/auth.ci.toml
